### PR TITLE
Include Styleguide::NavigationHelper to ensure it is available

### LINKED ISSUE #5: Ensure Styleguide::NavigationHelper is available in Styleguide::PagesController
While experimenting with the gem I regularly managed to receive this error:

NameError in Styleguide::Pages#show - undefined local variable or method `navigation' for Class ...

I can reproduce it by following these steps:

1) start rails server (freshly) bin/rails s
2) browse to a controller/action from my rails project e.g. localhost:3000/pages/index
3) browse to the styleguide e.g. localhost:3000/styleguide (thats where I mounted the engine)
 
The error occurs during the third step.

The error does not show up if I browse the styleguide immediately after starting the server.

### PR DESCRIPTION
**Pull request by msalzburg**
By explicitly including the Styleguide::NavigationHelper into the Styleguide::PagesController we can resolve #5

### CODE REVIEW

**Comment by juliaramstedt** [comment]
@jensljungblad I've run into this issue as well.

**Comment by jensljungblad** [comment]
I can reproduce this as well. Seems a bit weird that this should be necessary. I'll poke around a bit but will merge this if I don't find another solution. Thanks!

**Comment by msalzburg** [comment]
Any progress on this on? Otherwise a merge would be quite handsome ;) Thanks!

**Comment by jensljungblad** [comment]
Sorry, never had time to look at it! I'll merge this though, thanks for contributing!

**Pull request merged**
